import flet as ft

COLOR_BG = "#161616"
COLOR_FG = "#3B3B3B"
COLOR_TEXT = "#F3F3F3"

LABORATORY_ASSISTANT_SESSION_SECONDS = 120
LABORATORY_ASSISTANT_SESSION_WARNING_SECONDS = 30

TIMEOUT_DURATION = 10
TIME_MASK = "%Y-%m-%d %H:%M:%S"

ROLE = "laboratory_assistant"

USER_DATA_FILE = "user_data.json"

ORDER_DATA_EXPORT_FILE_NAME = "latest_orders"